version: '3'
services:
  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: penguins_db
      MYSQL_USER: airflow
      MYSQL_PASSWORD: airflow_password
    ports:
      - "3306:3306"
    networks:
      - airflow-network

  airflow:
    image: apache/airflow:2.2.3
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=mysql+mysqlconnector://airflow:airflow_password@mysql-db/penguins_db
    ports:
      - "8080:8080"
    networks:
      - airflow-network
    depends_on:
      - mysql-db

networks:
  airflow-network:
    driver: bridge
